/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TreesitterPlayground;

import java.io.File;

import ai.serenade.treesitter.Languages;
import ai.serenade.treesitter.Node;
import ai.serenade.treesitter.Parser;
import ai.serenade.treesitter.Tree;

public class App {
    static {
        File lib = new File("../parser/" + System.mapLibraryName("parser"));
        System.load(lib.getAbsolutePath());
    }

    public static void main(String[] args) {
        Parser parser = new Parser();
        parser.setLanguage(Languages.java());
        try {
            Tree tree = parser.parseString("class Hello {}");
            Node root = tree.getRootNode();
            System.out.println(root.getNodeString());

            
        } catch (Exception e) {} finally {
            parser.close();
        }
    }
}
